import { defineSchema, defineTable } from 'convex/server';
import { v } from 'convex/values';
import { agentTables } from './agent/schema';
import { aiTownTables } from './aiTown/schema';
import { conversationId, playerId } from './aiTown/ids';
import { engineTables } from './engine/schema';

export default defineSchema({
  music: defineTable({
    storageId: v.string(),
    type: v.union(v.literal('background'), v.literal('player')),
  }),

  messages: defineTable({
    conversationId,
    messageUuid: v.string(),
    author: playerId,
    text: v.string(),
    worldId: v.optional(v.id('worlds')),
  })
    .index('conversationId', ['worldId', 'conversationId'])
    .index('messageUuid', ['conversationId', 'messageUuid']),

  innerThoughts: defineTable({
    worldId: v.id('worlds'),
    playerId,
    text: v.string(),
    source: v.string(),
  }).index('player', ['worldId', 'playerId']),

  socialEvents: defineTable({
    worldId: v.id('worlds'),
    createdAt: v.number(),
    title: v.string(),
    description: v.string(),
    roomName: v.string(),
    participantIds: v.array(playerId),
    mbtiEventId: v.optional(v.id('mbtiEvents')),
    intensity: v.number(),
  })
    .index('by_world_time', ['worldId', 'createdAt'])
    .index('by_world', ['worldId']),

  mbtiExperiments: defineTable({
    createdAt: v.number(),
    updatedAt: v.number(),
    status: v.union(
      v.literal('creating'),
      v.literal('awaiting_user_responses'),
      v.literal('running'),
      v.literal('complete'),
      v.literal('failed'),
    ),
    question: v.string(),
    profile: v.object({
      code: v.string(),
      weights: v.object({
        e: v.number(),
        i: v.number(),
        s: v.number(),
        n: v.number(),
        t: v.number(),
        f: v.number(),
        j: v.number(),
        p: v.number(),
      }),
      behaviors: v.object({
        socialInitiation: v.number(),
        withdrawal: v.number(),
        factChecking: v.number(),
        meaningProjection: v.number(),
        logicFraming: v.number(),
        emotionalSensitivity: v.number(),
        closureNeed: v.number(),
        openness: v.number(),
        repairDrive: v.number(),
        rumination: v.number(),
      }),
    }),
    rolePresets: v.array(
      v.object({
        enabled: v.boolean(),
        role: v.string(),
        label: v.string(),
        mapping: v.optional(v.string()),
        mbtiCode: v.string(),
        traits: v.string(),
        reason: v.string(),
      }),
    ),
    observation: v.object({
      label: v.string(),
      runCount: v.number(),
      durationMs: v.optional(v.number()),
      targetEventCount: v.optional(v.number()),
    }),
    completedAt: v.optional(v.number()),
    runtimeArchivedAt: v.optional(v.number()),
    report: v.optional(
      v.object({
        generatedAt: v.number(),
        summary: v.string(),
        personalityFit: v.string(),
        evidence: v.array(v.string()),
        conclusion: v.string(),
        decisionInsights: v.optional(v.object({
          why: v.string(),
          changeConditions: v.string(),
          stableValue: v.string(),
          nextValidation: v.string(),
        })),
        decisionStructure: v.optional(v.object({
          surfaceQuestion: v.string(),
          underlyingDecision: v.string(),
          decisionDimensions: v.array(v.object({
            label: v.string(),
            whyItMatters: v.string(),
            userBlindSpot: v.optional(v.string()),
          })),
          personalityLevers: v.array(v.string()),
          unknowns: v.array(v.string()),
          hiddenNeeds: v.array(v.string()),
          riskBlindspots: v.array(v.string()),
          possiblePaths: v.array(v.object({
            label: v.string(),
            whenLikely: v.string(),
            possibleResult: v.string(),
          })),
          changeConditions: v.array(v.string()),
          nextValidationQuestions: v.array(v.string()),
        })),
        answerOptions: v.optional(v.array(v.object({
          label: v.string(),
          probability: v.number(),
          answer: v.string(),
          why: v.string(),
          signals: v.array(v.string()),
        }))),
        evidenceLevel: v.optional(v.union(
          v.literal('level_0'),
          v.literal('level_1'),
          v.literal('level_2'),
          v.literal('level_3'),
        )),
        realUserResponseCount: v.optional(v.number()),
        requiredUserResponseCount: v.optional(v.number()),
        missingUserResponseCount: v.optional(v.number()),
        confidenceNotice: v.optional(v.string()),
        limits: v.string(),
      }),
    ),
    worldId: v.id('worlds'),
    engineId: v.id('engines'),
    mapId: v.optional(v.id('maps')),
    townId: v.optional(v.id('mbtiTownProfiles')),
    sceneRequestId: v.optional(v.id('mbtiSceneRequests')),
    questionFocus: v.optional(
      v.object({
        coreQuestion: v.string(),
        drivingTension: v.string(),
        observationGoal: v.string(),
        decisionStructure: v.optional(v.object({
          surfaceQuestion: v.string(),
          underlyingDecision: v.string(),
          decisionDimensions: v.array(v.object({
            label: v.string(),
            whyItMatters: v.string(),
            userBlindSpot: v.optional(v.string()),
          })),
          personalityLevers: v.array(v.string()),
          unknowns: v.array(v.string()),
          hiddenNeeds: v.array(v.string()),
          riskBlindspots: v.array(v.string()),
          possiblePaths: v.array(v.object({
            label: v.string(),
            whenLikely: v.string(),
            possibleResult: v.string(),
          })),
          changeConditions: v.array(v.string()),
          nextValidationQuestions: v.array(v.string()),
        })),
        reasonablenessDiscussion: v.optional(v.object({
          plausibleInterpretation: v.string(),
          whyReasonable: v.array(v.string()),
          possibleMisreads: v.array(v.string()),
          assumptionsToConfirm: v.array(v.string()),
          alternativeFrames: v.array(v.string()),
          discussionPrompt: v.string(),
        })),
        validationTargets: v.optional(v.array(v.object({
          id: v.string(),
          label: v.string(),
          source: v.union(
            v.literal('decisionDimension'),
            v.literal('unknown'),
            v.literal('hiddenNeed'),
            v.literal('riskBlindspot'),
            v.literal('startupAnswer'),
          ),
          priority: v.union(v.literal('must'), v.literal('should'), v.literal('optional')),
          whatWouldTestIt: v.string(),
          badEventPattern: v.optional(v.string()),
        }))),
        analysisDimensions: v.optional(v.array(v.string())),
        designRationale: v.optional(v.string()),
        theoreticalBasis: v.optional(v.array(v.string())),
        evidenceTargets: v.array(v.string()),
        eventBeats: v.array(v.string()),
        startupQuestions: v.optional(v.array(v.object({
          question: v.string(),
          options: v.array(v.string()),
          maxSelections: v.optional(v.number()),
        }))),
        outcomeHypotheses: v.optional(v.array(v.object({
          label: v.string(),
          plainConclusion: v.string(),
          supportSignals: v.array(v.string()),
          weakSignals: v.array(v.string()),
        }))),
        eventPlans: v.optional(v.array(v.object({
          title: v.string(),
          severity: v.optional(v.string()),
          locationKey: v.optional(v.string()),
          scene: v.string(),
          trigger: v.string(),
          participants: v.array(v.string()),
          observationAxis: v.optional(v.string()),
          questionLink: v.optional(v.string()),
          informationGoal: v.string(),
          judgmentSignal: v.string(),
          coveredTargetIds: v.optional(v.array(v.string())),
          whyThisTestsIt: v.optional(v.string()),
          responseOptions: v.optional(v.array(v.string())),
          stakes: v.optional(v.object({
            timeCost: v.optional(v.string()),
            moneyCost: v.optional(v.string()),
            relationshipCost: v.optional(v.string()),
            opportunityCost: v.optional(v.string()),
          })),
          consequenceOptions: v.optional(v.array(v.object({
            userAction: v.string(),
            relationshipDelta: v.string(),
            unlocks: v.string(),
          }))),
        }))),
        resolutionCriteria: v.string(),
      }),
    ),
    decisionState: v.optional(v.object({
      updatedAt: v.number(),
      resolvedVariables: v.array(v.string()),
      uncertainVariables: v.array(v.string()),
      confirmedConstraints: v.array(v.string()),
      sensitiveConditions: v.array(v.string()),
      responseCoverage: v.object({
        responded: v.number(),
        required: v.number(),
        missing: v.number(),
      }),
      lastUserCorrection: v.optional(v.string()),
    })),
    agentInputIds: v.array(v.id('inputs')),
    socialField: v.optional(v.object({
      minimumAgents: v.number(),
      createdRoles: v.array(v.string()),
      eventSeed: v.number(),
    })),
  }).index('createdAt', ['createdAt']),

  mbtiEvents: defineTable({
    experimentId: v.id('mbtiExperiments'),
    worldId: v.id('worlds'),
    createdAt: v.number(),
    tickOffset: v.number(),
    scheduledDay: v.optional(v.number()),
    scheduledPhase: v.optional(v.union(
      v.literal('morning'),
      v.literal('afternoon'),
      v.literal('evening'),
      v.literal('night'),
    )),
    timelineTriggerReason: v.optional(v.string()),
    delayReason: v.optional(v.string()),
    kind: v.union(
      v.literal('pressure'),
      v.literal('opportunity'),
      v.literal('misunderstanding'),
      v.literal('evaluation'),
      v.literal('observer'),
    ),
    title: v.string(),
    description: v.string(),
    involvedRoles: v.array(v.string()),
    testedVariable: v.optional(v.string()),
    testedHypotheses: v.optional(v.array(v.string())),
    questionLink: v.optional(v.string()),
    informationGoal: v.optional(v.string()),
    coveredTargetIds: v.optional(v.array(v.string())),
    whyThisTestsIt: v.optional(v.string()),
    locationKey: v.optional(v.string()),
    stagingPoint: v.optional(v.object({
      x: v.number(),
      y: v.number(),
    })),
    expectedSignals: v.optional(v.array(v.string())),
    responseOptions: v.optional(v.array(v.string())),
    stakes: v.optional(v.object({
      timeCost: v.optional(v.string()),
      moneyCost: v.optional(v.string()),
      relationshipCost: v.optional(v.string()),
      opportunityCost: v.optional(v.string()),
    })),
    consequenceOptions: v.optional(v.array(v.object({
      userAction: v.string(),
      relationshipDelta: v.string(),
      unlocks: v.string(),
    }))),
    biasDirection: v.optional(v.union(
      v.literal('balanced'),
      v.literal('supporting'),
      v.literal('challenging'),
    )),
    probeOrigin: v.optional(v.union(
      v.literal('initial'),
      v.literal('adaptive'),
      v.literal('calibration'),
    )),
    adaptiveReason: v.optional(v.string()),
    residentRoles: v.optional(v.array(v.string())),
    residentParticipationGoal: v.optional(v.string()),
    status: v.union(
      v.literal('seeded'),
      v.literal('candidate'),
      v.literal('delayed'),
      v.literal('moving'),
      v.literal('conversation_pending'),
      v.literal('triggered'),
      v.literal('pending_user_response'),
      v.literal('observed'),
      v.literal('responded'),
      v.literal('skipped'),
      v.literal('expired_to_stage_report'),
      v.literal('resolved'),
      v.literal('failed'),
    ),
  })
    .index('experimentId', ['experimentId', 'createdAt'])
    .index('worldId', ['worldId', 'createdAt']),

  mbtiEventEvidence: defineTable({
    experimentId: v.id('mbtiExperiments'),
    mbtiEventId: v.id('mbtiEvents'),
    worldId: v.id('worlds'),
    createdAt: v.number(),
    occurredAt: v.number(),
    kind: v.union(
      v.literal('social_event'),
      v.literal('message'),
      v.literal('behavior'),
      v.literal('thought'),
    ),
    sourceId: v.optional(v.string()),
    participantIds: v.array(playerId),
    summary: v.string(),
    reason: v.string(),
  })
    .index('experiment_event', ['experimentId', 'mbtiEventId', 'createdAt'])
    .index('world_time', ['worldId', 'createdAt'])
    .index('source', ['worldId', 'kind', 'sourceId']),

  mbtiEventAssessments: defineTable({
    experimentId: v.id('mbtiExperiments'),
    mbtiEventId: v.id('mbtiEvents'),
    worldId: v.id('worlds'),
    createdAt: v.number(),
    updatedAt: v.number(),
    generatedAt: v.optional(v.number()),
    status: v.union(
      v.literal('pending'),
      v.literal('running'),
      v.literal('succeeded'),
      v.literal('failed'),
    ),
    evidenceCount: v.number(),
    evidenceSignature: v.string(),
    summary: v.optional(v.string()),
    inference: v.optional(v.string()),
    next: v.optional(v.string()),
    evidenceUsed: v.optional(v.array(v.string())),
    model: v.optional(v.string()),
    error: v.optional(v.string()),
  })
    .index('experiment_event', ['experimentId', 'mbtiEventId'])
    .index('world_time', ['worldId', 'updatedAt']),

  mbtiUserResponses: defineTable({
    experimentId: v.id('mbtiExperiments'),
    mbtiEventId: v.id('mbtiEvents'),
    createdAt: v.number(),
    updatedAt: v.number(),
    selectedOption: v.string(),
    confidence: v.number(),
    emotions: v.array(v.string()),
    freeText: v.string(),
    scenarioFit: v.union(
      v.literal('fits'),
      v.literal('partial'),
      v.literal('not_fit'),
    ),
    feedbackType: v.optional(v.union(
      v.literal('user_reaction'),
      v.literal('unrealistic_event'),
      v.literal('unrealistic_person'),
      v.literal('hit_real_issue'),
      v.literal('condition_correction'),
    )),
    correctionText: v.optional(v.string()),
    responseStatus: v.union(
      v.literal('responded'),
      v.literal('skipped'),
      v.literal('expired_to_stage_report'),
    ),
  })
    .index('experiment_event', ['experimentId', 'mbtiEventId'])
    .index('experiment_time', ['experimentId', 'createdAt']),

  mbtiBehaviorEvents: defineTable({
    experimentId: v.id('mbtiExperiments'),
    mbtiEventId: v.id('mbtiEvents'),
    worldId: v.id('worlds'),
    createdAt: v.number(),
    playerId,
    label: v.string(),
    description: v.string(),
  })
    .index('experiment_event', ['experimentId', 'mbtiEventId', 'createdAt'])
    .index('world_time', ['worldId', 'createdAt']),

  mbtiTownProfiles: defineTable({
    createdAt: v.number(),
    updatedAt: v.number(),
    slug: v.string(),
    name: v.string(),
    description: v.string(),
    status: v.union(v.literal('active'), v.literal('archived')),
    worldId: v.optional(v.id('worlds')),
  })
    .index('slug', ['slug'])
    .index('status', ['status']),

  mbtiTownLocations: defineTable({
    townId: v.id('mbtiTownProfiles'),
    key: v.string(),
    name: v.string(),
    affordances: v.array(v.string()),
    description: v.string(),
  })
    .index('town_key', ['townId', 'key'])
    .index('town', ['townId']),

  mbtiTownResidents: defineTable({
    townId: v.id('mbtiTownProfiles'),
    key: v.string(),
    name: v.string(),
    role: v.string(),
    mbtiCode: v.string(),
    weights: v.object({
      e: v.number(),
      i: v.number(),
      s: v.number(),
      n: v.number(),
      t: v.number(),
      f: v.number(),
      j: v.number(),
      p: v.number(),
    }),
    traits: v.array(v.string()),
    background: v.string(),
    defaultLocationKey: v.string(),
    scheduleTags: v.array(v.string()),
    status: v.union(v.literal('active'), v.literal('inactive')),
    lifeProfile: v.optional(
      v.object({
        longTermGoal: v.string(),
        currentPressure: v.string(),
        economy: v.number(),
        career: v.number(),
        social: v.number(),
        health: v.number(),
        stress: v.number(),
        updatedAt: v.optional(v.number()),
        lastImpactReason: v.optional(v.string()),
      }),
    ),
    playerId: v.optional(playerId),
    agentId: v.optional(v.string()),
    autonomyPlan: v.optional(
      v.object({
        updatedAt: v.number(),
        intent: v.string(),
        targetLocationKey: v.optional(v.string()),
        socialAppetite: v.number(),
        seekResidentKeys: v.array(v.string()),
        avoidResidentKeys: v.array(v.string()),
        topicSeed: v.string(),
        reason: v.string(),
      }),
    ),
  })
    .index('town_key', ['townId', 'key'])
    .index('town_status', ['townId', 'status'])
    .index('town_location', ['townId', 'defaultLocationKey']),

  mbtiRelationships: defineTable({
    townId: v.id('mbtiTownProfiles'),
    residentAKey: v.string(),
    residentBKey: v.string(),
    familiarity: v.number(),
    trust: v.number(),
    warmth: v.number(),
    tension: v.number(),
    influence: v.number(),
    summary: v.string(),
    lastInteractionAt: v.optional(v.number()),
    updatedAt: v.number(),
  })
    .index('town_pair', ['townId', 'residentAKey', 'residentBKey'])
    .index('town_resident_a', ['townId', 'residentAKey'])
    .index('town_resident_b', ['townId', 'residentBKey']),

  mbtiTownMemories: defineTable({
    townId: v.id('mbtiTownProfiles'),
    createdAt: v.number(),
    updatedAt: v.number(),
    kind: v.union(
      v.literal('public'),
      v.literal('conflict'),
      v.literal('favor'),
      v.literal('rumor'),
      v.literal('routine'),
      v.literal('scene'),
      v.literal('user'),
    ),
    salience: v.number(),
    title: v.string(),
    summary: v.string(),
    residentKeys: v.array(v.string()),
    locationKey: v.optional(v.string()),
    status: v.union(v.literal('active'), v.literal('stale')),
    staleAt: v.optional(v.number()),
    stalenessReason: v.optional(v.string()),
    sourceSceneRequestId: v.optional(v.id('mbtiSceneRequests')),
    sourceKind: v.optional(v.union(
      v.literal('seed'),
      v.literal('scene'),
      v.literal('autonomy_tick'),
      v.literal('user_entry'),
      v.literal('reflection'),
    )),
    sourceReason: v.optional(v.string()),
    relationshipDelta: v.optional(v.object({
      relationshipId: v.id('mbtiRelationships'),
      familiarity: v.number(),
      trust: v.number(),
      warmth: v.number(),
      tension: v.number(),
      influence: v.number(),
      reason: v.string(),
    })),
  })
    .index('town_status', ['townId', 'status'])
    .index('town_kind', ['townId', 'kind'])
    .index('town_time', ['townId', 'createdAt']),

  mbtiTownTimelineEvents: defineTable({
    townId: v.id('mbtiTownProfiles'),
    createdAt: v.number(),
    updatedAt: v.number(),
    townDay: v.number(),
    phase: v.union(
      v.literal('morning'),
      v.literal('afternoon'),
      v.literal('evening'),
      v.literal('night'),
    ),
    dayProgress: v.number(),
    scope: v.union(
      v.literal('resident_life'),
      v.literal('resident_work'),
      v.literal('relationship'),
      v.literal('question_probe'),
    ),
    storyline: v.union(
      v.literal('public'),
      v.literal('conflict'),
      v.literal('favor'),
      v.literal('rumor'),
      v.literal('routine'),
      v.literal('scene'),
      v.literal('user'),
    ),
    source: v.union(
      v.literal('autonomy_tick'),
      v.literal('scene'),
      v.literal('question_probe'),
      v.literal('reflection'),
    ),
    title: v.string(),
    summary: v.string(),
    residentKeys: v.array(v.string()),
    locationKey: v.optional(v.string()),
    memoryId: v.optional(v.id('mbtiTownMemories')),
    relationshipId: v.optional(v.id('mbtiRelationships')),
    sceneRequestId: v.optional(v.id('mbtiSceneRequests')),
    mbtiEventId: v.optional(v.id('mbtiEvents')),
    status: v.union(v.literal('active'), v.literal('superseded')),
  })
    .index('town_day', ['townId', 'townDay', 'phase'])
    .index('town_time', ['townId', 'createdAt'])
    .index('town_scope', ['townId', 'scope', 'createdAt']),

  mbtiTownConversationRequests: defineTable({
    townId: v.id('mbtiTownProfiles'),
    createdAt: v.number(),
    updatedAt: v.number(),
    status: v.union(
      v.literal('pending'),
      v.literal('started'),
      v.literal('skipped'),
      v.literal('expired'),
    ),
    residentKeys: v.array(v.string()),
    residentNames: v.array(v.string()),
    locationKey: v.optional(v.string()),
    topicSeed: v.string(),
    priority: v.union(v.literal('low'), v.literal('medium'), v.literal('high')),
    reason: v.string(),
    sourceMemoryId: v.optional(v.id('mbtiTownMemories')),
    worldId: v.optional(v.id('worlds')),
    sceneRequestId: v.optional(v.id('mbtiSceneRequests')),
    startedAt: v.optional(v.number()),
    skipReason: v.optional(v.string()),
  })
    .index('town_status', ['townId', 'status'])
    .index('town_time', ['townId', 'createdAt']),

  mbtiSceneRequests: defineTable({
    townId: v.id('mbtiTownProfiles'),
    createdAt: v.number(),
    updatedAt: v.number(),
    status: v.union(
      v.literal('planned'),
      v.literal('running'),
      v.literal('complete'),
      v.literal('failed'),
    ),
    userQuestion: v.string(),
    userEntryMode: v.union(
      v.literal('solo'),
      v.literal('with_partner'),
      v.literal('with_friend'),
      v.literal('with_partner_and_friend'),
    ),
    sceneType: v.string(),
    selectedLocationKey: v.string(),
    selectedResidentKeys: v.array(v.string()),
    sceneResidentRoles: v.optional(v.array(v.object({
      residentKey: v.string(),
      relationToUser: v.string(),
      sceneReason: v.string(),
      personalStake: v.string(),
      knowsAboutUser: v.array(v.string()),
      doesNotKnow: v.array(v.string()),
      pressureStyle: v.string(),
      allowedIntervention: v.string(),
    }))),
    questionFocus: v.optional(
      v.object({
        coreQuestion: v.string(),
        drivingTension: v.string(),
        observationGoal: v.string(),
        decisionStructure: v.optional(v.object({
          surfaceQuestion: v.string(),
          underlyingDecision: v.string(),
          decisionDimensions: v.array(v.object({
            label: v.string(),
            whyItMatters: v.string(),
            userBlindSpot: v.optional(v.string()),
          })),
          personalityLevers: v.array(v.string()),
          unknowns: v.array(v.string()),
          hiddenNeeds: v.array(v.string()),
          riskBlindspots: v.array(v.string()),
          possiblePaths: v.array(v.object({
            label: v.string(),
            whenLikely: v.string(),
            possibleResult: v.string(),
          })),
          changeConditions: v.array(v.string()),
          nextValidationQuestions: v.array(v.string()),
        })),
        reasonablenessDiscussion: v.optional(v.object({
          plausibleInterpretation: v.string(),
          whyReasonable: v.array(v.string()),
          possibleMisreads: v.array(v.string()),
          assumptionsToConfirm: v.array(v.string()),
          alternativeFrames: v.array(v.string()),
          discussionPrompt: v.string(),
        })),
        validationTargets: v.optional(v.array(v.object({
          id: v.string(),
          label: v.string(),
          source: v.union(
            v.literal('decisionDimension'),
            v.literal('unknown'),
            v.literal('hiddenNeed'),
            v.literal('riskBlindspot'),
            v.literal('startupAnswer'),
          ),
          priority: v.union(v.literal('must'), v.literal('should'), v.literal('optional')),
          whatWouldTestIt: v.string(),
          badEventPattern: v.optional(v.string()),
        }))),
        analysisDimensions: v.optional(v.array(v.string())),
        designRationale: v.optional(v.string()),
        theoreticalBasis: v.optional(v.array(v.string())),
        evidenceTargets: v.array(v.string()),
        eventBeats: v.array(v.string()),
        startupQuestions: v.optional(v.array(v.object({
          question: v.string(),
          options: v.array(v.string()),
          maxSelections: v.optional(v.number()),
        }))),
        outcomeHypotheses: v.optional(v.array(v.object({
          label: v.string(),
          plainConclusion: v.string(),
          supportSignals: v.array(v.string()),
          weakSignals: v.array(v.string()),
        }))),
        eventPlans: v.optional(v.array(v.object({
          title: v.string(),
          severity: v.optional(v.string()),
          locationKey: v.optional(v.string()),
          scene: v.string(),
          trigger: v.string(),
          participants: v.array(v.string()),
          observationAxis: v.optional(v.string()),
          questionLink: v.optional(v.string()),
          informationGoal: v.string(),
          judgmentSignal: v.string(),
          coveredTargetIds: v.optional(v.array(v.string())),
          whyThisTestsIt: v.optional(v.string()),
          responseOptions: v.optional(v.array(v.string())),
          stakes: v.optional(v.object({
            timeCost: v.optional(v.string()),
            moneyCost: v.optional(v.string()),
            relationshipCost: v.optional(v.string()),
            opportunityCost: v.optional(v.string()),
          })),
          consequenceOptions: v.optional(v.array(v.object({
            userAction: v.string(),
            relationshipDelta: v.string(),
            unlocks: v.string(),
          }))),
        }))),
        resolutionCriteria: v.string(),
      }),
    ),
    selectionRationale: v.array(v.string()),
    ephemeralParticipantKeys: v.array(v.string()),
    worldId: v.optional(v.id('worlds')),
    experimentId: v.optional(v.id('mbtiExperiments')),
    townRelationshipDeltas: v.optional(
      v.array(
        v.object({
          residentAKey: v.string(),
          residentBKey: v.string(),
          trust: v.number(),
          warmth: v.number(),
          tension: v.number(),
          reason: v.string(),
        }),
      ),
    ),
  })
    .index('town_time', ['townId', 'createdAt'])
    .index('town_status', ['townId', 'status']),

  ...agentTables,
  ...aiTownTables,
  ...engineTables,
});
